workflows : 重新整理，统一格式，master不开启缓存

diff --git a/.github/workflows/21.02-rockchip.yml b/.github/workflows/21.02-rockchip.yml
--- a/.github/workflows/21.02-rockchip.yml
+++ b/.github/workflows/21.02-rockchip.yml
@@ -17,8 +17,8 @@ on:
   repository_dispatch:
   workflow_dispatch:
   #schedule:
-  # - cron: 0 20 * * 2
-   #   分,时,日,月,星期。每周 三 20时执行一次 (UTC时间)
+  # - cron: 0 18 * * 2
+   #   分,时,日,月,星期。每周 三 18时执行一次 (UTC时间)
   
 env:
   REPO_URL: https://github.com/immortalwrt/immortalwrt
@@ -54,10 +54,12 @@ jobs:
         chmod +x $ENV_SH && $ENV_SH
         sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo timedatectl set-timezone "$TZ"
+        docker image prune -a -f
+        docker container prune -f
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
 
-    - name: 检查空间使用情况
+    - name: 检查空间使用情况1
       if: (!cancelled())
       run: df -hT
 
@@ -71,14 +73,14 @@ jobs:
       uses: klever1988/cachewrtbuild@main
       with:
         ccache: 'true'
-        mixkey: 'openwrt21'
+        mixkey: '21.02-rockchip'
         prefix: ${{ github.workspace }}/openwrt
 
     - name: 更新 & 安装 feeds & 执行脚本
       run: |
         cd openwrt
-        ./scripts/feeds update -a && ./scripts/feeds update -a
-        ./scripts/feeds install -a && ./scripts/feeds install -a
+        ./scripts/feeds update -a
+        ./scripts/feeds install -a
         chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
         chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
         chmod +x $GITHUB_WORKSPACE/$DIY_SH && $GITHUB_WORKSPACE/$DIY_SH
@@ -86,20 +88,19 @@ jobs:
 
     - name: 导入补丁和配置 & 下载文件
       run: |
-        [ -e files ] && mv files openwrt/files
+        [ -d files ] && mv files openwrt/files || echo "files not found"
         cat configs/Platform-rockchip.txt >> openwrt/.config
         cat configs/Packages.txt >> openwrt/.config
-        sed -i '$a CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_SingBox=n' openwrt/.config
-        [ -e $UBOOT_PATCH2 ] && mv $UBOOT_PATCH2 openwrt/package/boot/uboot-rockchip/patches
+        [ -f $UBOOT_PATCH2 ] && mv $UBOOT_PATCH2 openwrt/package/boot/uboot-rockchip/patches
         mv patchs/openwrt21/target/*.patch openwrt/target/linux/rockchip/patches-5.4
-        [ -e $USB3_FILE ] && mv $USB3_FILE openwrt/target/linux/rockchip/files/drivers/phy/rockchip
+        [ -f $USB3_FILE ] && mv $USB3_FILE openwrt/target/linux/rockchip/files/drivers/phy/rockchip
         cd openwrt
         make defconfig
         make download -j8 V=10
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;
 
-    - name: 编译固件中
+    - name: 编译固件
       id: compile
       run: |
         cd openwrt
@@ -107,7 +108,7 @@ jobs:
         make -j$(($(nproc)+1)) || make -j$(nproc) || make -j1 V=s
         echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: 空间使用情况
+    - name: 空间使用情况2
       if: (!cancelled())
       run: df -hT
 
@@ -143,11 +144,11 @@ jobs:
       if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
       run: |
         echo -e "✅ Rockchip 平台 21.02 源码\nℹ 第一次长时间无法启动可尝试重启或重刷\n🍃 如出现不稳定可尝试cpu降频" >> release.txt
-        echo "release_tag=$(date +"%Y.%m.%d-Rockchip_21.02")" >> $GITHUB_OUTPUT
+        echo "release_tag=$(date +"%Y.%m.%d-21.02_Rockchip")" >> $GITHUB_OUTPUT
         echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: 上传固件发布
-      uses: softprops/action-gh-release@v0.1.15
+    - name: 上传固件到发布
+      uses: softprops/action-gh-release@v2.0.4
       if: steps.tag.outputs.status == 'success' && !cancelled()
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -156,19 +157,19 @@ jobs:
         body_path: release.txt
         files: ${{ env.FIRMWARE }}/*
 
-    - name: 删除旧发布的固件
-      uses: dev-drprasad/delete-older-releases@v0.2.1
+    - name: 删除以前发布的固件
+      uses: dev-drprasad/delete-older-releases@v0.3.3
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
       with:
-        keep_latest: 10
+        keep_latest: 15
         delete_tags: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: 删除过时工作流程
+    - name: 删除以前的工作流程
       uses: Mattraks/delete-workflow-runs@v2
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: ${{ github.repository }}
         retain_days: 1
-        keep_minimum_runs: 3
+        keep_minimum_runs: 5
diff --git a/.github/workflows/23.05-X86.yml b/.github/workflows/23.05-X86.yml
--- a/.github/workflows/23.05-X86.yml
+++ b/.github/workflows/23.05-X86.yml
@@ -17,14 +17,13 @@ on:
   repository_dispatch:
   workflow_dispatch:
   schedule:
-   - cron: 0 23 * * 5
-   #   分,时,日,月,星期。每周六 23时执行一次 (UTC时间)
+   - cron: 0 20 * * 4
+   #   分,时,日,月,星期。每周五 20时执行一次 (UTC时间)
   
 env:
   REPO_URL: https://github.com/immortalwrt/immortalwrt
   REPO_BRANCH: openwrt-23.05
-  PLATFORM_FILE: configs/Platform-x86.txt
-  CONFIG_FILE: configs/Packages-lite.txt
+  CONFIG_FILE: configs/Packages.txt
   FREE_DISK_SH: scripts/free_disk_space.sh
   ENV_SH: scripts/environment.sh
   SETTINGS_SH: scripts/init-settings.sh
@@ -48,10 +47,10 @@ jobs:
         DEBIAN_FRONTEND: noninteractive
       run: |
         chmod +x $FREE_DISK_SH && $FREE_DISK_SH
-        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo -E apt-get -qq update -y
         sudo -E apt-get -qq full-upgrade -y
         chmod +x $ENV_SH && $ENV_SH
+        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo timedatectl set-timezone "$TZ"
         docker image prune -a -f
         docker container prune -f
@@ -68,26 +67,26 @@ jobs:
         git clone $REPO_URL -b $REPO_BRANCH openwrt
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
 
-    # - name: 开启缓存
-    #   uses: klever1988/cachewrtbuild@main
-    #   with:
-    #     ccache: 'true'
-    #     mixkey: 'openwrt-X86'
-    #     prefix: ${{ github.workspace }}/openwrt
+    - name: 开启缓存
+      uses: klever1988/cachewrtbuild@main
+      with:
+        ccache: 'true'
+        mixkey: '23.05-X86'
+        prefix: ${{ github.workspace }}/openwrt
 
     - name: 更新 & 安装 feeds & 执行脚本
       run: |
         cd openwrt
-        ./scripts/feeds update -a && ./scripts/feeds update -a
+        ./scripts/feeds update -a
+        ./scripts/feeds install -a
         chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
         chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
         chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH
-        ./scripts/feeds install -a && ./scripts/feeds install -a
 
     - name: 导入补丁和配置 & 下载文件
       run: |
-        [ -e files ] && mv files openwrt/files
-        [ -e $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
+        [ -d files ] && mv files openwrt/files || echo "files not found"
+        [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
         cd openwrt
         make defconfig
         make download -j8 V=10
@@ -98,6 +97,7 @@ jobs:
       id: compile
       run: |
         cd openwrt
+        make defconfig
         echo -e "$(($(nproc)+1)) thread compile"
         make -j$(($(nproc)+1)) || make -j$(nproc) || make -j1 V=s
         echo "status=success" >> $GITHUB_OUTPUT
@@ -141,7 +141,7 @@ jobs:
         echo "release_tag=$(date +"%Y.%m.%d-23.05_x86")" >> $GITHUB_OUTPUT
         echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: 上传固件发布
+    - name: 上传固件到发布
       uses: softprops/action-gh-release@v2.0.4
       if: steps.tag.outputs.status == 'success' && !cancelled()
       env:
@@ -155,7 +155,7 @@ jobs:
       uses: dev-drprasad/delete-older-releases@v0.3.3
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
       with:
-        keep_latest: 10
+        keep_latest: 15
         delete_tags: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -166,4 +166,4 @@ jobs:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: ${{ github.repository }}
         retain_days: 1
-        keep_minimum_runs: 3
+        keep_minimum_runs: 5
diff --git a/.github/workflows/23.05-rockchip.yml b/.github/workflows/23.05-rockchip.yml
--- a/.github/workflows/23.05-rockchip.yml
+++ b/.github/workflows/23.05-rockchip.yml
@@ -17,18 +17,19 @@ on:
   repository_dispatch:
   workflow_dispatch:
   # schedule:
-  #  - cron: 0 19 * * 1
-   #   分,时,日,月,星期。每周 二 19时执行一次 (UTC时间)
+  #  - cron: 0 20 * * 2
+   #   分,时,日,月,星期。每周 三 20时执行一次 (UTC时间)
   
 env:
   REPO_URL: https://github.com/immortalwrt/immortalwrt
   REPO_BRANCH: openwrt-23.05
   PLATFORM_FILE: configs/Platform-rockchip.txt
-  CONFIG_FILE: configs/Packages-lite.txt
+  CONFIG_FILE: configs/Packages.txt
   FREE_DISK_SH: scripts/free_disk_space.sh
   ENV_SH: scripts/environment.sh
-  DIY_SH: scripts/O23-SNAPSHOT/diy.sh
-  CLASH_CORE: scripts/preset-clash-core.sh
+  SETTINGS_SH: scripts/init-settings.sh
+  PACKAGES_SH: scripts/packages.sh
+  CLASH_CORE_SH: scripts/preset-clash-core-arm64.sh
   UBOOT_DTS: patchs/openwrt23/uboot/rk3328-orangepi-r1-plus-lts-u-boot.dtsi
   TARGET_PATCH: patchs/openwrt23/target/9999-add-missing-parameters-for-LTS.patch
   USB3_FILE: patchs/usb3/phy-rockchip-inno-usb3.c
@@ -50,10 +51,10 @@ jobs:
         DEBIAN_FRONTEND: noninteractive
       run: |
         chmod +x $FREE_DISK_SH && $FREE_DISK_SH
-        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo -E apt-get -qq update -y
         sudo -E apt-get -qq full-upgrade -y
         chmod +x $ENV_SH && $ENV_SH
+        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo timedatectl set-timezone "$TZ"
         docker image prune -a -f
         docker container prune -f
@@ -80,20 +81,20 @@ jobs:
     - name: 更新 & 安装 feeds & 执行脚本
       run: |
         cd openwrt
-        ./scripts/feeds update -a && ./scripts/feeds update -a
+        ./scripts/feeds update -a
+        ./scripts/feeds install -a
         chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
         chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
         chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH
-        ./scripts/feeds install -a && ./scripts/feeds install -a
 
     - name: 导入补丁和配置 & 下载文件
       run: |
-        [ -e files ] && mv files openwrt/files
-        [ -e $CPLATFORM_FILE ] && cat $PLATFORM_FILE >> openwrt/.config
-        [ -e $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
-        [ -e $UBOOT_DTS ] && mv $UBOOT_DTS openwrt/package/boot/uboot-rockchip/src/arch/arm/dts
-        [ -e $TARGET_PATCH ] && mv $TARGET_PATCH openwrt/target/linux/rockchip/patches-5.15
-        [ -e $USB3_FILE ] && mv $USB3_FILE openwrt/target/linux/rockchip/files-5.15/drivers/phy/rockchip
+        [ -d files ] && mv files openwrt/files || echo "files not found"
+        [ -f $CPLATFORM_FILE ] && cat $PLATFORM_FILE >> openwrt/.config
+        [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
+        [ -f $UBOOT_DTS ] && mv $UBOOT_DTS openwrt/package/boot/uboot-rockchip/src/arch/arm/dts
+        [ -f $TARGET_PATCH ] && mv $TARGET_PATCH openwrt/target/linux/rockchip/patches-5.15
+        [ -f $USB3_FILE ] && mv $USB3_FILE openwrt/target/linux/rockchip/files-5.15/drivers/phy/rockchip
         cd openwrt
         make defconfig
         make download -j8 V=10
@@ -202,7 +203,7 @@ jobs:
         echo "release_tag=$(date +"%Y.%m.%d-23.05_rockchip")" >> $GITHUB_OUTPUT
         echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: 上传固件发布
+    - name: 上传固件到发布
       uses: softprops/action-gh-release@v2.0.4
       if: steps.tag.outputs.status == 'success' && !cancelled()
       env:
@@ -216,7 +217,7 @@ jobs:
       uses: dev-drprasad/delete-older-releases@v0.3.3
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
       with:
-        keep_latest: 10
+        keep_latest: 15
         delete_tags: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -227,4 +228,4 @@ jobs:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: ${{ github.repository }}
         retain_days: 1
-        keep_minimum_runs: 3
+        keep_minimum_runs: 5
diff --git a/.github/workflows/master-mtkfilogic.yml b/.github/workflows/master-mtkfilogic.yml
--- a/.github/workflows/master-mtkfilogic.yml
+++ b/.github/workflows/master-mtkfilogic.yml
@@ -17,12 +17,14 @@ on:
   repository_dispatch:
   workflow_dispatch:
   schedule:
-   - cron: 0 22 * * 6
-   #   分,时,日,月,星期。每周 日 22时执行一次 (UTC时间)
+   - cron: 0 22 * * 3
+   #   分,时,日,月,星期。每周 四 22时执行一次 (UTC时间)
   
 env:
   REPO_URL: https://github.com/immortalwrt/immortalwrt
   REPO_BRANCH: master
+  PLATFORM_FILE: configs/Platform-filogic.txt
+  CONFIG_FILE: configs/Packages-reduce.txt
   FREE_DISK_SH: scripts/free_disk_space.sh
   ENV_SH: scripts/environment.sh
   SETTINGS_SH: scripts/init-settings.sh
@@ -51,10 +53,12 @@ jobs:
         chmod +x $ENV_SH && $ENV_SH
         sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo timedatectl set-timezone "$TZ"
+        docker image prune -a -f
+        docker container prune -f
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
 
-    - name: 检查空间使用情况
+    - name: 检查空间使用情况1
       if: (!cancelled())
       run: df -hT
 
@@ -64,42 +68,42 @@ jobs:
         git clone $REPO_URL -b $REPO_BRANCH openwrt
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
 
-    - name: 开启缓存
-      uses: klever1988/cachewrtbuild@main
-      with:
-        ccache: 'true'
-        mixkey: 'master-filogic'
-        prefix: ${{ github.workspace }}/openwrt
+    # - name: 开启缓存
+    #   uses: klever1988/cachewrtbuild@main
+    #   with:
+    #     ccache: 'true'
+    #     mixkey: 'master-filogic'
+    #     prefix: ${{ github.workspace }}/openwrt
 
     - name: 更新 & 安装 feeds & 执行脚本
       run: |
         cd openwrt
-        ./scripts/feeds update -a && ./scripts/feeds update -a
+        ./scripts/feeds update -a
+        ./scripts/feeds install -a
         chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
         chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
-        ./scripts/feeds install -a && ./scripts/feeds install -a
+        chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH
 
     - name: 导入补丁和配置 & 下载文件
       run: |
-        [ -e files ] && mv files openwrt/files
-        cat configs/Platform-filogic.txt >> openwrt/.config
-        cat configs/Packages-reduce.txt >> openwrt/.config
+        [ -d files ] && mv files openwrt/files || echo "files not found"
+        [ -f $CPLATFORM_FILE ] && cat $PLATFORM_FILE >> openwrt/.config
+        [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
         cd openwrt
         make defconfig
         make download -j8 V=10
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;
 
-    - name: 编译固件中
+    - name: 编译固件
       id: compile
       run: |
         cd openwrt
-        make defconfig
         echo -e "$(($(nproc)+1)) thread compile"
         make -j$(($(nproc)+1)) || make -j$(nproc) || make -j1 V=s
         echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: 空间使用情况
+    - name: 空间使用情况2
       if: (!cancelled())
       run: df -hT
 
@@ -137,7 +141,7 @@ jobs:
         echo "release_tag=$(date +"%Y.%m.%d-master_filogic")" >> $GITHUB_OUTPUT
         echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: 上传固件发布
+    - name: 上传固件到发布
       uses: softprops/action-gh-release@v2.0.4
       if: steps.tag.outputs.status == 'success' && !cancelled()
       env:
@@ -147,19 +151,19 @@ jobs:
         body_path: release.txt
         files: ${{ env.FIRMWARE }}/*
 
-    - name: 删除旧发布的固件
+    - name: 删除以前发布的固件
       uses: dev-drprasad/delete-older-releases@v0.3.3
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
       with:
-        keep_latest: 10
+        keep_latest: 15
         delete_tags: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: 删除过时工作流程
+    - name: 删除以前的工作流程
       uses: Mattraks/delete-workflow-runs@v2
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: ${{ github.repository }}
         retain_days: 1
-        keep_minimum_runs: 3
+        keep_minimum_runs: 5
diff --git a/.github/workflows/master-rockchip.yml b/.github/workflows/master-rockchip.yml
--- a/.github/workflows/master-rockchip.yml
+++ b/.github/workflows/master-rockchip.yml
@@ -17,12 +17,14 @@ on:
   repository_dispatch:
   workflow_dispatch:
 #  schedule:
-  # - cron: 0 20 * * 5
-   #   分,时,日,月,星期。每周 六 20时执行一次 (UTC时间)
+  # - cron: 0 22 * * 2
+   #   分,时,日,月,星期。每周 三 22时执行一次 (UTC时间)
   
 env:
   REPO_URL: https://github.com/immortalwrt/immortalwrt
   REPO_BRANCH: master
+  PLATFORM_FILE: configs/Platform-rockchip.txt
+  CONFIG_FILE: configs/Packages.txt
   FREE_DISK_SH: scripts/free_disk_space.sh
   ENV_SH: scripts/environment.sh
   SETTINGS_SH: scripts/init-settings.sh
@@ -51,6 +53,8 @@ jobs:
         chmod +x $ENV_SH && $ENV_SH
         sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo timedatectl set-timezone "$TZ"
+        docker image prune -a -f
+        docker container prune -f
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
 
@@ -64,27 +68,27 @@ jobs:
         git clone $REPO_URL -b $REPO_BRANCH openwrt
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
 
-    - name: 开启缓存
-      uses: klever1988/cachewrtbuild@main
-      with:
-        ccache: 'true'
-        mixkey: 'master-rockchip'
-        prefix: ${{ github.workspace }}/openwrt
+    # - name: 开启缓存
+    #   uses: klever1988/cachewrtbuild@main
+    #   with:
+    #     ccache: 'true'
+    #     mixkey: 'master-rockchip'
+    #     prefix: ${{ github.workspace }}/openwrt
 
     - name: 更新 & 安装 feeds & 执行脚本
       run: |
         cd openwrt
-        ./scripts/feeds update -a && ./scripts/feeds update -a
+        ./scripts/feeds update -a
+        ./scripts/feeds install -a
         chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
         chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
         chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH
-        ./scripts/feeds install -a && ./scripts/feeds install -a
 
     - name: 导入补丁和配置 & 下载文件
       run: |
-        [ -e files ] && mv files openwrt/files
-        cat configs/Platform-rockchip.txt >> openwrt/.config
-        cat configs/Packages.txt >> openwrt/.config
+        [ -d files ] && mv files openwrt/files || echo "files not found"
+        [ -f $CPLATFORM_FILE ] && cat $PLATFORM_FILE >> openwrt/.config
+        [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
         cd openwrt
         make defconfig
         make download -j8 V=10
@@ -193,8 +197,8 @@ jobs:
         echo "release_tag=$(date +"%Y.%m.%d-master_rockchip")" >> $GITHUB_OUTPUT
         echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: 上传固件发布
-      uses: softprops/action-gh-release@v0.1.15
+    - name: 上传固件到发布
+      uses: softprops/action-gh-release@v2.0.4
       if: steps.tag.outputs.status == 'success' && !cancelled()
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -203,19 +207,19 @@ jobs:
         body_path: release.txt
         files: ${{ env.FIRMWARE }}/*
 
-    - name: 删除旧发布的固件
-      uses: dev-drprasad/delete-older-releases@v0.2.1
+    - name: 删除以前发布的固件
+      uses: dev-drprasad/delete-older-releases@v0.3.3
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
       with:
-        keep_latest: 10
+        keep_latest: 15
         delete_tags: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: 删除过时工作流程
+    - name: 删除以前的工作流程
       uses: Mattraks/delete-workflow-runs@v2
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: ${{ github.repository }}
         retain_days: 1
-        keep_minimum_runs: 3
+        keep_minimum_runs: 5
